# Generated by Django 2.0.4 on 2018-04-10 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='bookmark_text',
            new_name='bookmark_name',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
