# Generated by Django 2.0.2 on 2018-04-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20180411_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='pub_date',
        ),
    ]
