# Generated by Django 2.0.4 on 2018-04-12 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_remove_bookmark_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='id',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
