# Generated by Django 2.0.4 on 2018-04-24 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hasBeenRead', models.BooleanField(default=False)),
                ('timeRead', models.DateTimeField()),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fromUser', to=settings.AUTH_USER_MODEL)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='toUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
